src/models/app_configuration.js
src/models/git.js

This fixes issue #2
Note that I would have liked to call `nodegit.Repository.open` for each tested folder instead of checking if `candidatePath/.git` is a directory but error handling in nodegit can be displeasing.
(I ran the tests this time, everything is ok :) )

Support being called from a subdirectory

---

package.json
spec/git.spec.js
src/models/git.js

Update nodegit to 0.5.0.
This fixes issue #10.

Bump nodegit to 0.5.0

---

package.json
scripts/install-autocomplete.sh
scripts/postinstall.sh
scripts/uninstall-autocomplete.sh

A trivial fix to package.json and some scripts enhancement/cleanups

Scripts cleanup

---

src/models/log.js

The ``build succeeded in`` message appears for dedicated builds. This PR shows it as a success message.

Display the message "build succeeded in" as a success one

---

bin/clever.js
src/commands/deploy.js

Replaces `clever deploy --redeploy`.

Add `clever restart`. Fixes #34

---

spec/log.spec.js
src/models/log.js

Reconnect the Websocket if websocket has been closed (mostly happen when the remote server closes it or if the connection dropped)

Logs: reconnect websocket if connection has been closed

---

bin/clever.js
src/models/app_configuration.js

Default application

---

package.json
spec/application.app.js
spec/scale.spec.js
src/commands/activity.js
src/commands/addon.js
src/commands/applications.js
src/commands/domain.js
src/commands/status.js
src/logger.js
src/models/addon.js
src/models/app_configuration.js
src/models/application.js
src/models/env.js
src/models/interact.js

The major bump here is `lodash@^4.0.0`

bump dependencies

---

spec/open-browser.spec.js
src/commands/login.js
src/models/domain.js
src/open-browser.js

Fix OpenBrowser and `clever open` behaviour

---

src/models/log.js

Fix arguments passed to getContinuousLogs when reconnecting

---

bin/clever.js
src/commands/create.js
src/models/application.js

Add `--github` option to `clever create` to create a github-based app

---

README.md
src/models/application.js

replace apache+php with php

---

bin/clever.js
spec/parsers.spec.js
src/commands/addon.js
src/commands/create.js
src/commands/link.js
src/models/addon.js
src/models/app_configuration.js
src/models/application.js
src/models/organisation.js
src/parsers.js

More consistent handling of apps, orgas and addons ids / names

---

spec/domain.spec.js
src/models/domain.js

Add tests and extract the pure logic from `getBest`

Privilege custom cleverapps domains in `Domain.getBest`

---

src/commands/env.js

Fix `clever env import` (issue #89)

---

src/commands/makeDefault.js

Fix `clever make-default` (issue #88)

---

spec/logger.spec.js
src/logger.js

as well as tests for processApiError

Better support for CCAPI error messages

---

bin/clever.js
src/commands/notifications.js
src/models/notification.js
src/models/user.js

Webhooks management

---

bin/clever.js
src/commands/ssh.js
src/models/configuration.js

Add `clever ssh command`

---

package.json

That should fix travis problems with node 7

nodegit: bump to 0.17.0

---

src/models/git.js

Better error message when there is no code to deploy

---

src/models/git.js

Use a temporary remote if necessary, instead of failing

---

bin/clever.js
src/commands/logs.js
src/models/log.js

Keyword search for logs

---

package.json
src/models/addon.js

New invoicing support

---

bin/clever.js
src/commands/login.js

Allow non-interactive login

---

src/commands/addon.js

eg:
```
Addon fsbucket-acme (id:addon_b423d27f-f99f-46fa-b4e9-8d7d1abe27e7|realId:bucket_c28cf254-0134-407e-a8f1-f51505c08e61) successfully created
```

It allows to display addonId and realId

---

src/models/events.js
src/models/log.js
src/models/ws_stream.js

- automatic reconnection
- keep alive messages

Factor out WS connections for logs and events

---

spec/application.spec.js
src/models/app_configuration.js
src/models/application.js
src/models/git.js

Fix slugification of app name/alias used for the git remote name

---

package-lock.json
package.json
src/commands/env.js
src/models/env.js

I just tried to mimick what was being done with addon env vars. I need to dig to understand what I did.
Let me know if the wording about app dependencies is correct.

Display app dependencies environment variables in `clever env`

---

bin/clever.js
src/commands/profile.js
src/models/user.js

Fixes #161
No unit test, do we need one for this kind of stuffs?
Looks like this:

Add "clever profile" command

---

package.json
spec/git.spec.js
src/commands/deploy.js
src/models/git.js

* Fix wrong coercion with some short commit ids (especially those looking like an exponential)
* Resolve full commit ids through local git repo
Fixes #167

Fix "clever restart" with short commit ids

---

bin/clever.js
src/commands/ssh.js

I took the opportunity to refactor/cleanup the ssh command a bit...
Fixes #164.

Add key param for ssh command

---

src/commands/deploy.js
src/models/git.js

While working on #132 we failed to implement the enhancement but we succeeded in making some small refactorings :smile:

Refactor on deploy/push

---

src/commands/create.js
src/models/app_configuration.js
src/models/application.js

Ignore parent ".clever.json" with `clever create`

---

README.md
scripts/release-job.sh

Update install and packaging docs

---

nodegit/nodegit.md
scripts/build-release.js

Fix bad libcurl on linux build

---

spec/git.spec.js
src/commands/deploy.js
src/models/git.js

This commit required a pretty big refactor:
* Enforce ES6 features (const, fat arrows, destructuring...)
* Try to harmonize and unify Bacon streams (and error handling)
* Safer usage of "colors" package
Fixes #195
Fixes #197

WIP: Exit process with code 1 on deployment errors

---

src/commands/deploy.js
src/logger.js

Display "clever restart --commit [commit-id]" + color refactoring

---

bin/clever.js
package-lock.json
package.json

Use forked version of update-notifier which relies on GitHub tags

---

spec/app_configuration.spec.js
spec/configuration.spec.js
src/commands/applications.js
src/commands/login.js
src/commands/makeDefault.js
src/commands/profile.js
src/commands/ssh.js
src/models/api.js
src/models/app_configuration.js
src/models/configuration.js
src/models/drain.js
src/models/events.js
src/models/git.js
src/models/log.js
src/models/notification.js
src/models/user.js

Refactor for:
* profile
* makeDefault
* ssh
* applications

Issue 202 error handling small commands

---

src/commands/cancel-deploy.js
src/models/deployment.js

* ES6+
* command stream handler

Refactor cancel-deployment

---

spec/drain.spec.js
src/models/drain.js

Fix drain creation authorization

---

README.md
scripts/build-release.js

Publish rpm and deb to bintray

---

bin/clever.js
src/commands/login.js
src/commands/logout.js
src/models/configuration.js

Added logout command #223

---

src/models/configuration.js

Use env vars CLEVER_TOKEN and CLEVER_SECRET when present for API oAuth

---

package-lock.json
package.json

Update isomorphic-git (enable pushing submodules)

---

README.md

Fix issues detected for Linux and macos install process in README.md

Fix `.tar.gz` install documentation

---

Jenkinsfile
scripts/job-publish-dockerhub.js
scripts/utils.js
templates/dockerhub/Dockerfile

Add a docker image for the clever tools and publish it on dockerhub

---

src/commands/activity.js

Fix wrong activity display for WIP

---

src/models/ws-stream.js

Limit the number of retries for when the WebSocket connexion fails

---

src/commands/status.js

Fix the code that determines the activation of auto scalability.

Fix wrong auto-scalability setting in clever status #322

---

bin/clever.js
src/commands/open.js
src/models/domain.js

`clever open` to open in https:// #221

---

src/commands/deploy.js
src/commands/restart.js
src/models/git.js

Display commits doing clever deploy #333

---

src/command-promise-handler.js
src/logger.js
src/models/app_configuration.js
src/models/fs-utils.js
src/models/git.js

Find `.git` repos recursively through parent dirs

---

src/commands/deploy.js

Fix git commit diplay just before a deploy (for new empty repos)

---

src/commands/restart.js

Fix `clever restart` for empty repos

---

src/models/send-to-api.js

We'll just wait for the release of the clever-client with this feature...

Use new retry option on superagent.request

---

bin/clever.js
package-lock.json
package.json
src/commands/accesslogs.js
src/models/accesslogs.js
src/models/addon.js
src/models/configuration.js
src/models/send-to-api.js
src/parsers.js

Add accesslogs command

---

src/commands/scale.js
src/models/application.js

Fix `clever scale --build-flavor`

---

bin/clever.js
src/commands/accesslogs.js

Fix accesslogs params and add alias

---

src/models/drain.js

Fix drain type autocomplete

---

CHANGELOG.md
spec/configuration.spec.js
src/commands/diag.js
src/commands/login.js
src/commands/logout.js
src/models/configuration.js
src/models/git.js
src/models/send-to-api.js

Fix `login` and `logout` commands, update mkdirp usage

---

src/models/application.js

Requires a new clever-client release

fix clever link

---

bin/clever.js
package-lock.json
package.json
src/commands/tcp-redirs.js
src/models/organisation.js
src/parsers.js

This requires a new version of the clever-client

Add clever tcp-redirs command

---

bin/clever.js
src/commands/config.js
src/models/application_configuration.js

introduce clever config subcommand

---

README.md

Hi,
I added a note for each distribution that uses Bintray to warn about it's end. 
Happy review :wink:

Add bintray warning note

---

README.md

A simple one liner to use inside a Dockerfile :slightly_smiling_face:

Add Dockerfile section

---

src/models/accesslogs.js
src/models/configuration.js
src/models/fs-utils.js

conf: move configuration file inside a clever-cloud directory

---

README.md
src/models/drain.js

This merge request adds a new drain type for NewRelic.
I also implemented the mandatory API key option for this drain.

Add NewRelic drain

---

Jenkinsfile
scripts/config.js
scripts/job-build.js
scripts/job-package.js
scripts/utils.js
templates/gpg/.rpmmacros

- Added some pretty colored messages at start/end of tasks ;)
- Added some required variables for GPG sign.
- Added gpg setup and gpg sign to the scripts, as well as .rpmmacros
file generation.
- Not using fpm's --rpm-sign, but directly rpm --add-sign as per: https://github.com/jordansissel/fpm/issues/1720

Added rpm signature.

---

bin/clever.js
src/commands/database.js

Fix and improve several details for clever database

---

src/models/format-ng-table.js

Here is a full example of the results.

Fix ng term

---

CHANGELOG.md
src/models/addon.js

This step is no longer needed, and it will be removed from the API.

Skip preorder add-on step.

---

bin/clever.js

I know it was ordered by "domain" like `link` is followed by `unlink` but I find it hard to read, WDYT?

order commands

---

CHANGELOG.md
src/commands/diag.js
src/models/configuration.js

feat(diag): add config file and auth source to clever diag

---

bin/clever.js

Fix text in helper

---

src/commands/deploy.js

feat(deploy): log application and owner details

---

package-lock.json
package.json
src/models/git.js
src/models/isomorphic-http-with-agent.js

 fix: pass an HTTP agent without timeout to isomorphic-git

---

RELEASE.md
scripts/config.js
scripts/publish-dockerhub.js

ci(docker): build and publish docker image to Docker Hub

---

README.md
src/models/application.js

- Add `grahds` region in autocomplete
- Add `grahds` region in documentation

Add references to new grahds region

---

package-lock.json
package.json

chore(deps): bump @clevercloud/client to v8.1.2

---

docs/addons-backups.md
docs/applications-deployment-lifecycle.md

- Add `addon create --format` reference
- Add `deploy --tag` reference
- Add `create --format` reference
- fixes

docs: update according to 3.4.0 release

---

README.md
docs/applications-management.md
src/models/application.js

Remove reference to `jed` as we move to a private region

docs: reflect middle east evolution

---

bin/clever.js
src/commands/drain.js
src/models/drain.js

Closes #695.
I'm sure you have a proper way to optionally print the index in the drain list ;).

add indexPrefix customization for ElasticSearch log drain

---

bin/clever.js
package-lock.json
package.json
src/commands/curl.js

feat (curl): list command, add help details

---

bin/clever.js
src/commands/create.js
src/commands/status.js
src/models/application.js
src/parsers.js

feat (applications): add the ability to create as a task

---

templates/arch/PKGBUILD

chore: fix PKGBUILD template for arch build

---

README.md
package-lock.json
package.json
rollup-curlconverter.config.js
src/commands/curl.js
vendors/README_VENDORS.md
vendors/curlconverter-parse.js

fix(curl): fix clever curl command when used with the auto packaged binary version

---

package.json

Fixes #729
This PR adds the vendor directory to the files that should be included in the npm package.

fix(build): fix npm package

---

RELEASE.md

docs(release): clarify RELEASE.md

---

.github/workflows/preview.yml

ci(preview): update SHA in preview comment when PR is updated

---

src/commands/addon.js
src/models/addon.js

feat(addon create): choose the cheapest plan by default

---

bin/clever.js

feat: add a --no-color option

---

bin/clever.js

Fix #649 
I checked the code is OK printing the `this.disabled` value of the `update-notifier` package

fix (update-notifier): change behavior

---

src/commands/addon.js

Prepare Alpha public access for Keycloak.
Better manage Alpha/Beta message after an add-on creation. One is added for Pulsar.

docs(addon): better manage alpha/beta providers

---

bin/clever.js
package-lock.json
package.json
src/commands/activity.js
src/commands/addon.js
src/commands/diag.js
src/commands/drain.js
src/commands/env.js
src/commands/notify-email.js
src/commands/profile.js
src/commands/published-config.js
src/commands/service.js
src/commands/status.js
src/commands/tcp-redirs.js
src/commands/webhooks.js
src/models/application.js

feat: support --format for all commands

---

bin/clever.js
src/commands/applications.js
src/models/application.js

feat: list all applications

---

bin/clever.js

fix(drain): remove double --addon option

---

bin/clever.js
docs/applications-config.md
docs/applications-deployment-lifecycle.md
src/command-options.js

Also reorder some options (`--format` always at the end for example)

docs: update some texts

---

bin/clever.js

Replace lazyRequire calls with regular require

---

src/commands/addon.js

Add warning texts for incoming Metabase add-on

docs: add metabase add-on creation warning

---

src/models/addon.js

feat(addon): enable string value for defined option keys

---

docs/addons-backups.md
src/commands/addon.js
src/models/app_configuration.js

This PR: 
- Add a "." at the end of the "no app found" sentence
- Add a mention in documentation of post-creation instruction for add-ons
- Add default credentials at Keycloak creation (explaining user will be invited to change password)

3.9 release fix

---

src/commands/profile.js
src/models/user.js

Fixes #668 
_Note: date format is the same as the one used in the console_

chore: add token expiry to clever profile

---

bin/clever.js
docs/README.md
package-lock.json
package.json
src/clever-client/auth-bridge.js
src/commands/addon.js
src/commands/curl.js
src/commands/profile.js
src/commands/tokens.js
src/experimental-features.js
src/models/configuration.js
src/models/send-to-api.js
src/parsers.js
src/prompt-password.js

```
clever tokens create "[TOKEN NAME]"
```
You will be prompted for your password (and MFA code if necessary) and get this result:
```
✔ API token created successfully!
- API token ID : [API_TOKEN_ID]
- API token    : [API_TOKEN]
- Expiration   : [EXPIRATION_DATE]
Export this token and use it to make authenticated requests to the Clever Cloud API through the Auth Bridge:
export CC_API_TOKEN=[API_TOKEN]
curl -H "Authorization: Bearer $CC_API_TOKEN" https://auth-bridge.clever-cloud.com/v2/self
Then, to revoke this token, run:
clever tokens revoke [API_TOKEN_ID]
```
```
clever tokens
// or
clever tokens list
```
You will get this result:
```
┌─────────┬──────────────────┬─────────────┬─────────────────────┬────────────────────┬──────────────────────┐
│ (index) │ API token ID     │    Name …
```

add clever tokens command to manage API tokens

---

docs/README.md
docs/ng.md
docs/setup-systems.md

docs(ng): after release update

---

src/lib/slugify.js
src/models/app_configuration.js
src/models/git.js

fix(deploy): fix app naming on deployment

---

src/models/app_configuration.js

When doing the QA of the #862, I discoverd that unlinking an application after setting it as default with `make-default` wasn't deleting the `default` key in `.clever.json`. This was then leading to an execution error execting user to manually clean its `.clever.json` file

fix(unlink): remove default when unlinking default app

---

docs/README.md
docs/applications-config.md
docs/operators.md

Depends on last 3.13 release adjustements

docs: update for 3.13 release
