CleverCloud/clever-tools

src/commands/deploy.js
If the ssh-agent is running but the ssh key wasn't added with ssh-add, the error message will be "Error authenticating:" without more details.
=> Better error message when ssh-agent isn't aware of the ssh key

scripts/install-autocomplete.sh, scripts/postinstall.sh, scripts/uninstall-autocomplete.sh
We use a lot of bashisms, hence do not try to use any posix shell.
sh is dash on ubuntu, which doesn't support half the things we use.
fixes #26
Signed-off-by: Marc-Antoine Perennou <Marc-Antoine@Perennou.com>
=> scripts: explicitely use bash

src/models/application.js
The API response to GET /products/instances will change a bit and include a new field:
```json
"variant": {
"id": "<uuid>",
"slug": "variant-slug",
"name": "Variant Name"
}
```
We need to change how to check the instance availability when creating an application: we need to not only check the instance type but also the variant slug.
=> Handle image variant in instance types list.

package.json, src/models/git.js
This adds support for node 6 and don't seem to impact other things despite the breaking changes.
Also, nodegit will follow node versions, meaning that all LTS will be covered and 0.x branches support will be dropped. 
#52 should be fine after this PR
=> nodegit: bump to 0.13.1

bin/clever.js, src/commands/login.js, src/commands/open.js, src/models/domain.js, src/open-browser.js
Fixes #43 
Extracts the browser opening logic from clever login in a more reusable module.
Fixes an issue with domain names and path_begin filtering.
=> Implement `clever open`

bin/clever.js, src/commands/applications.js
`list` was not descriptive enough
Fixes #31
=> Rename `list` command to `applications`

bin/clever.js, src/commands/addon.js, src/commands/open.js, src/commands/service.js, src/models/addon.js, src/models/application.js
Harmonize addon management under `clever addon`. Addon management does not
accept `--alias` since addon management is organisation-wide.
`clever addon` commands now all take a `--org` option to specify the
organisation. Only `clever addon create` takes a `--link` option (akin to
`--alias`).
=> Implement service dependencies management with `clever service`

bin/clever.js
This will avoid changes in `bin/clever.js` when updating version
=> use package version from package.json

package.json
No more node-expat compilation with clever-client 0.3.1
=> Update clever-client to 0.3.1

.travis.yml, package.json
deprecated since january 2017
nodegit doesn't provide binaries for node 0.12 anymore
more and more deps are complaining that they expect >=4
this speeds up travis checks a lot
=> drop support for node 0.12

scripts/install-autocomplete.sh, scripts/uninstall-autocomplete.sh
The autocomplete scripts will be added to /usr/local/share instead of /usr/share
=> Add MacOS case

bin/clever.js, src/commands/deploy.js, src/commands/logs.js, src/models/log.js
Allow to only fetch logs for a given deployment with `clever logs --deployment-id`
Only display logs for the current deployment in `clever deploy` and `clever restart`
Fixes #42 
Also fixes #130 as it changes the way deployment events are filtered
=> WIP: Logs deploymentId

src/commands/addon.js, src/commands/service.js
Display `realId` of the add-on when calling `clever service`: because when I call `clever env`, I can't get an environment variable for the linked fs-bucket of an application.
It's useful if you want to generate a `bucket.json` file.
Display `realId` of the add-on when calling `clever addon create ...` (same reason)
=> Display `realId` of the add-on

README.md
Current README suggests installing `openssl-dev`.
I couldn find any package with its name:
See for instance:
- [debian search](https://packages.debian.org/search?keywords=openssl-dev&searchon=names&suite=stable&section=all)
- [user not finding it in a severfault post](https://serverfault.com/questions/249340/install-openssl-dev-on-ubuntu-server)
The proper package should be `libssl-dev` (see [package presentation](https://packages.debian.org/stretch/libssl-dev)).
=> Fix libssl package name for apt based systems

src/logger.js
This fixes remove usage of `console.debug` and `console.warn` to use `console.log` for everything except for errors (where we use `console.error`).
I also took the liberty to refactor some sutffs:
* Add `use_strict`
* Use some ES6+ goodies like spread, const or arrow functions
* Remove bind calls since `console` is a namespace like `Math` or `JSON`
More infos on the "autobind" behaviour:
* https://bugs.chromium.org/p/chromium/issues/detail?id=167911
* https://bugs.webkit.org/show_bug.cgi?id=157286
* https://github.com/whatwg/console/issues/3#issuecomment-254363388
* https://console.spec.whatwg.org/#console-namespace
* https://wpt.fyi/console
FYI, it works on Chrome, Node, Safari, FF but not yet in Edge.
Fixes #134.
=> Only use console.log & console.error

src/commands/deploy.js
This is a quick fix, it may deserve some refactoring on the way we use the `s_commitId` Bacon stream.
Fixes #145.
=> Show commit about to be redeployed

bin/clever.js, src/commands/version.js
Currently, we have `--version` but we do not have a `version` subcommand which is quite common in projets using subcommands like us
=> add "clever version"

src/commands/activity.js, src/commands/login.js, src/commands/profile.js
=>  Display unspecified name in bold red for `clever login` and `clever  profile`

src/models/drain.js
We keep the management of them, but creation is now unavailable.
=> remove datadog tcp creation drain, add new datadog http drain creation

src/commands/activity.js
This PR will hopefully fix #306
=> fix(activity): avoid using cursor when stdout is not a tty

src/commands/service.js
Fix application alias parameter when using 'service link-app'.
=> Fix clever service link-app #320

src/models/configuration.js
* All commands load the configuration file
* If the conf file does not exist yet, an info is logged
* The code used to log that info was breaking when CLI was packaged :thinking:
=> Fix issue when config dir does not exist

bin/clever.js, src/commands/notify-email.js
`clever notify-email add --help` reads:
```
Usage: clever notify-email add --notify <EMAIL_ADDRESS>|<USER_ID>|ORGANISATION NAME
```
So people write "ORGANISATION". The code was only allowing for "organisation" (lowercase).
This PR fixes it.
Also, the help text is weird and people may read `"organisation name"` instead of `"…|organisation" name`
=> WIP: Fix match of target string when it is "organisation".

bin/clever.js, package.json, src/commands/env.js, src/commands/published-config.js, src/models/variables.js
This is a follow-up of the work started by @clementd-fretlink in https://github.com/CleverCloud/clever-tools/pull/326
NOTES: Some code will be move in the clever-client to be also used in the clever-components:
* https://github.com/CleverCloud/clever-client.js/issues/28
* https://github.com/CleverCloud/clever-components/issues/97
=> Add `--json` option to `clever env` and `clever published-config`

bin/clever.js
Running `clever config --help` displays the following message:
```
Available Commands:
get                        Get the current configuration
set                        Set the configuration
update                     Update the configuration
```
Here it's not clear what's the difference between `set` and `update`.
=> Clarify `config set` / `config update` description

src/commands/addon.js
I have a custom add-on provider that doesn't have a description. Even though this is my fault and every providers should have a description, it could happen that one day, a provider doesn't have one. :)
=> Addon providers: don't fail listing if add-on's description is null

src/models/log.js
isCleverMessage was checked in isDeploymentSuccessMessage and isDeploymentFailedMessage, but not isBuildSucessMessage.
=> Fix isCleverMessage check in isBuildSucessMessage

src/models/app_configuration.js
The generated file `.clever.json` could be formatted with indentations for readability convenience.
=> format .clever.json for readability

src/models/accesslogs.js
Fix #399
After this fix, if the source object isn't defined, the log will appear as:
```
2020-11-02T16:31:36.512Z [ 10.2.204.148 ] GET console.clever-cloud.com /ping 304
```
I removed the localization part entirely because the `-` symbol is used as a delimiter in the extended format, not as a missing data symbol like it is in the CLF format.
I don't know if the extended log is meant to be parsed. If it is, how can we replace the source field? Using a `unknown` placeholder text? Or `missing`?
=> Access logs: handle possibly undefined source object

bin/clever.js, package-lock.json, package.json, src/commands/accesslogs.js, src/commands/addon.js, src/commands/cancel-deploy.js, src/commands/config.js, src/commands/deploy.js, src/commands/domain.js, src/commands/drain.js, src/commands/env.js, src/commands/notify-email.js, src/commands/published-config.js, src/commands/status.js, src/commands/stop.js, src/commands/tcp-redirs.js, src/commands/webhooks.js, src/models/activity.js, src/models/addon.js, src/models/application.js, src/models/configuration.js, src/models/deployments.js, src/models/domain.js, src/models/log.js, src/models/organisation.js, src/models/user.js
This PR does two things that are a bit linked, I could split it in two, you tell me your preferences. This also updates the clever-client to the 7.x branch.
This is linked to #449 .
First, the `clever addon providers show <provider>` will now display available versions and features for each plan, when available. An example with Elasticsearch that has multiple options available
```
Plan xs                  
CPUs: 1                    
DISK: 10 GB                
MEMORY: 1 GB                      
NODES: 1              
Type: Dedicated            
Available versions: 6, 7 (default)
Options for version 6:     
kibana: default=false
apm: default=false              
encryption: default=false
Options for version 7:     
kibana: default=false           
apm: default=false       
encryption: …
```
=> Add-on: list versions and options of a specific provider, create add-on with available options

src/models/log.js
=> Fix `clever deploy` which was displaying logs from runtime instances

package.json
https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/
=> Fix colors version to 1.4.0

README.md
The deb instruction doesn't set arch resulting in warnings when using `apt update`. This PR fix this.
=> Update README to set arch in deb install instruction

README.md
When you don't read the documentation carefully, you end up with the wrong zone for your datadog drain.
Providing 2 different commands let the reader pick the one that fits his/her needs.
=> Provide datadoghq.eu drain url as an example

.gitignore, CHANGELOG.md, bin/clever.js, src/commands/addon.js, src/commands/database.js, src/get-output-format-option.js, src/models/accesslogs.js, src/models/addon.js, src/models/configuration.js, src/models/ids-resolver.js, src/parsers.js
Closes #584
This PR is based on the collective work of @Nowadays, @leyour-m and @lenglet-k in https://github.com/CleverCloud/clever-tools/pull/447.
We adjusted a few details (see issue #584) but the main goal is the same.
This PR also contains the introduction of the `ids-resolver` which can:
* resolve an owner ID from:
* an app ID
* an add-on ID
* a real ID
* resolve an add-on ID from a real ID
* resolve a real ID from an add-on ID
This resolver is used in the new `clever addon env`, it is also introduced in `clever database backups` commands.
We'll use it in the other commands in the future.
This PR also contains a helper function to declare command line options with limited possible values for output format (`human` by default and `json`).
=> Add command to get add-on env

CHANGELOG.md, package-lock.json, package.json
=> restart/deploy: Fix Node.js < 18.16 abort bug

README.md, bin/clever.js, src/models/application.js
This is a combination of 3 PRs from @davlgd:
* https://github.com/CleverCloud/clever-tools/pull/622
* https://github.com/CleverCloud/clever-tools/pull/623
* https://github.com/CleverCloud/clever-tools/pull/624
Bonus:
* Adjusted the commit messages
* Created a `AVAILABLE_ZONES` constant to reuse the list in `clever.js`
* Added a commit to add meteor in the README
=> Update zones and runtimes lists

src/commands/create.js, src/models/app_configuration.js
=> fix: add an alias/name check during app create

src/commands/applications.js, src/models/app_configuration.js
It's done when app is created or its informations queried. 
It will only work for newly linked/created apps
Fix #619
=> feat (applications): add git+ssh URL in local config data

.github/workflows/build.yml, scripts/archive.js, scripts/build.js, scripts/bundle.js, scripts/cellar-client.js, scripts/config.js, scripts/job-build.js, scripts/job-preview.js, scripts/job-publish.js, scripts/paths.js, scripts/publish-arch.js, scripts/publish-brew.js, scripts/publish-cellar.js, scripts/publish-dockerhub.js, scripts/publish-exherbo.js, scripts/publish-nexus.js, scripts/publish-npm.js, scripts/utils.js, src/commands/create.js, src/commands/deploy.js
=> ci: enable eslint

package-lock.json, package.json, src/models/log-v4.js, src/models/send-to-api.js
* Update @clevercloud/client to 8.0.3 to get all the small bug fixes around retry and network failures
* Enable auto retry on network failures (we forgot to enable it when we switched to the new logs API)
* Improve open and error debug message (wording and colors)
* Only print SSE errors as debug when verbose mode is enabled
* Improve error message with `EAI_AGAIN` and `ECONNRESET`
I also took the opportunity to fix/refactor a few details in the code (see commits).
Download the preview binary and test `clever logs`:
* Without time window
* With just `--since`
* With just `--until`
* With both `--since` and `--until`
* Try to cut your internet connection for more than 20 secs
* Try to cut your internet connection for a few seconds (or switch between 2 network interfaces)
* The logs stream …
=> Fix bugs on clever logs and enable retry

.github/workflows/build.yml, .github/workflows/publish.yml
=> ci: fix fpm installation by using ruby 3.3 instead of 2.7

bin/clever.js, src/commands/addon.js, src/commands/create.js
=> feat(applications): use current directory as default create name 

bin/clever.js, docs/README.md, docs/addons-backups.md, docs/applications-config.md, docs/applications-deployment-lifecycle.md, docs/applications-management.md, docs/nexus-config.md, docs/services-depedencies.md, docs/services-logs-drains.md, docs/services-notifications-webhooks.md, docs/setup-systems.md
It's an initial version, open to comments. Feel free to modify it widely.
=> doc: new Clever Tools documentation

bin/clever.js, package-lock.json, package.json, src/commands/deploy.js, src/models/git.js
=> feat(deploy): support tag option

src/models/log-v4.js
If a user is asking for a `--quiet` restart, he still have lots of messages: 
```
Restarting astropaperga on commit xxx
Waiting for deployment to start…
Deployment started (deployment_xxx)
Waiting for application logs…
Deployment successful
```
This fix disable "Waiting messages" and keep only those about deployment starting/result
=> fix: quieter mode during restart

bin/clever.js, src/commands/database.js
As mentioned in https://github.com/CleverCloud/clever-tools/issues/589 implement format option for the `clever database backups` command
=> feat(backups): support JSON format when plotting a backup list

bin/clever.js, src/commands/addon.js
As mentioned in https://github.com/CleverCloud/clever-tools/issues/589 implement format option for the `clever addon` command
=> feat(addon): support JSON format when plotting an add-on list

src/commands/addon.js
MateriaDB KV server now need a TLS connection, so we need to add `--tls` to the connect command we show after the creation of an add-on.
=> Add TLS to MateriaDB KV connect info

bin/clever.js
closes #719
This PR revert the JSON format introduced for the `clever addon` command in https://github.com/CleverCloud/clever-tools/pull/697. This introduces a new `clever addon list` command. This sub-command could use a custom format (human or json) to plot all add-ons of an owner. 
To handle option already set in main command in a sub-command, we would need to work on a cliparse patch to allow an option overwrites.
=> fix(addon): allow json format in new list subcommand

src/commands/activity.js
Fixes #430
Fixes #193
This PR displays the deployment id in the output table.
Before:
```
2024-04-16T13:02:20+02:00  OK           DEPLOY     af81a57abe99c43a47527ddfdda9a12833189d88  Git
2024-04-16T13:22:44+02:00  OK           DEPLOY     fa491d14d320a9acf70fb7fb7482959ea527e5fa  Git
2024-04-16T13:33:02+02:00  OK           DEPLOY     7fe5c8b4cbdccf4e763f2eb4b798bc5c442e659b  Git
```
After:
```
2024-04-16T13:02:20+02:00  deployment_6c931b46-0275-4935-8f1d-04b4d26f878a  OK           DEPLOY     af81a57abe99c43a47527ddfdda9a12833189d88  Git
2024-04-16T13:22:44+02:00  deployment_bf87aed5-f95e-4936-bcd7-f13bacf23491  OK           DEPLOY     fa491d14d320a9acf70fb7fb7482959ea527e5fa  Git
2024-04-16T13:33:02+02:00  deployment_b1f77ac7-2fec-4b5a-b1b2-5981a84575e0  OK           DEPLOY …
```
=> feat(activity): add deployment id

docs/setup-systems.md
As discussed with the CLI team and within the #738, this PR removes the section about Nix setup.
Once the package is available on nixpkgs, we'll reintroduce a section about it.
=> docs(setup-systems): remove nix instructions

src/commands/activity.js
Fixes the following bug:
- run `clever activity --follow`
- restart the app
- :boom: the parsing of the event coming from the event API is broken
This regression has been introduced by commit 094ce7c9
=> fix(activity): fix activity list refresh when `--follow` options is enabled

bin/clever.js, src/commands/accesslogs.js, src/commands/activity.js, src/commands/cancel-deploy.js, src/commands/config.js, src/commands/console.js, src/commands/delete.js, src/commands/domain.js, src/commands/drain.js, src/commands/env.js, src/commands/logs.js, src/commands/open.js, src/commands/published-config.js, src/commands/restart.js, src/commands/scale.js, src/commands/service.js, src/commands/ssh.js, src/commands/status.js, src/commands/stop.js, src/commands/tcp-redirs.js, src/models/app_configuration.js, src/models/application.js, src/models/namespaces.js, src/models/organisation.js
Fixes #587
This PR adds the support of `--app` and `--org` options in all commands where an app is involved.
- `--app` can be an app_id or an app_name.
The first commit adds a smart app resolver which aim is to provide an app ID and owner ID from an `--app` or an `--alias`.
The following commits add the options to the commands and use the smart resolver.
=> feat: support --app option

src/commands/console.js
This PR has been rebased on `support-app-id` from Pierre
=> feat(console): open the Console even if no app is linked

bin/clever.js, src/command-options.js, src/commands/deploy.js, src/commands/restart.js, src/models/exit-strategy-option.js, src/models/log-v4.js, src/models/log.js
As discussed in #319 implements the `exit-on` option for the `deploy` command. 
For the `timeout`, we should first consider how we support duration (as seen in #609). 
I opened an issue for the timeout option: #693 
closes #319
=> feat(deploy): add the support of exit-on option

README.md, docs/setup-systems.md
Fixes #748
The `clever-tools` package is now available directly on `nixpkgs - unstable`.
This PR simply updates the docs to reflect that.
=> docs(setup-systems): reintroduce nix

bin/clever.js
Fixes #812
This PR enables the `isGlobal` flag of the `update-notifier` as discussed with @davlgd.
The update message now rightfully specifies to use `npm i -g` instead of `npm i`
=> fix(update-notifier): set `isGlobal` to `true`

package-lock.json, package.json
`text-table` is an essential dependency so it should not be part of `devDependencies`.
When installing `clever-tools` with `NODE_ENV="production"`, the `text-table` was not being installed which cause issues (for instance within the `nix` package).
This is a `fix` and not a `chore` commit because this actually makes the nix package broken for commands relying on the `text-table` dependency.
Fixes #819
=> fix(dependencies): remove `text-table` from `devDependencies`

src/commands/addon.js, src/models/addon.js
This PR: 
- add a `findByName` function in add-ons model, to find an add-on only by its name
- look for orgId by add-on ID or name if none is specified
Fixes #811
=> fix: addon delete without org parameter

bin/clever.js, docs/applications-config.md, package-lock.json, package.json, src/commands/domain.js, src/models/app_configuration.js, src/models/node-dns-resolver.js
- Adds a `clever domain diag [--app {appId|appName}] [--domain {string}] [-F json]` command,
- This command allows users to get diagnostics about DNS configs for every domain associated to a given app,
Some important context:
- we throw errors and tell users their DNS config is wrong when:
- no config was found (no CNAME / no A records),
- the config contains at least one unknown record (a record that does not match the default Load Balancer config of the app).
- APEX domains can only be configured with A records so diagnostics for such domains will never mention CNAME records,
- we don't support configs relying on a CDN (like Cloudflare for instance) and we don't support private Load Balancers for now (no API).
- You should probably review the PR from the client first: …
=> feat(domain): init diag command

src/commands/addon.js
I've added Matomo as beta, its current status, and declared KC/Metabase as beta after their update. This commit was based on refactor branch
=> fix(addon): update Beta providers list

src/commands/addon.js, src/models/addon.js
For add-ons with a public management URL, we tell the user what the URL is at creation, to ease onboarding. For that I added add-on env to returned object after creation (we'll move this to API side in a future iteration). 
I've only done this for KC, Matomo, Metabase for now, but we'll can go further for other add-ons too. This commit was based on refactor branch
=> feat(addon): add URL to use/manage add-on at creation

src/commands/domain.js
- Removes the `sortDomains` function from the `domains.js` file,
- Use the `sortDomains` callback provided by the client project (this way the sort order matches the one used within the component project). 
Not essential but it would make sense.
If it's not part of the 3.9.0 it's perfectly fine, it's just a tiny refactor.
=> refactor(domains/diagApplication): rely on `sortDomains` from the client

bin/clever.js, docs/applications-config.md, src/commands/domain.js
=> feat(domain): introduce domain overview command

src/commands/domain.js
- Adds a missing space between the record and the text "from (...)" when there are invalid A records coming from a CNAME
In prod:
With the fix:
=> fix(domain): add missing spacing within diag report

bin/clever.js, src/models/addon.js, src/parsers.js
This PR allows the support of elastic plug-ins at creation in Clever Tools. As this option is a comma-separated list, I separate options from pairs, looking for a `,` followed by a word and a `=` and matching it. 
It also adds a parser to add-ons options. It will help us to clean all this in a future release. Here I stay minimal on change to lower impact. 
I've tested it with multiple options, single options, comma-separated options, no options, and it seems working fine.
=> feat(addon): elastic plugins option support

src/parsers.js
This PR: 
- Manage options name with `-` in the option parser
- Single option case (then options is a string, checked as an array of char)
This should fix #855 @francoisfreitag can you confirm?
=> fix(addon): error with options parsing

bin/clever.js, src/commands/features.js, src/experimental-features.js, src/models/configuration.js
Bootstrap the features flags management implementation, open to discussion
fix #774
=> feat(features): add experimental features management

rollup.config.js
Fixes #864
- Fixes the `npm run build` command on MacOS.
The rollup build fails because:
- the whole `curlconverter` module is imported,
- the `curlconverter` codebase relies on `nunjucks` to handle `ansible`, `yaml`, etc. but not `JSON` (and I believe that's the only one we actually use),
- `nunjucks` relies on `chokidar`,
- when building on MacOS, `chokidar` relies on the `fsevents` package which is essentially a binary file (`fsevents.node`) built specifically for `darwin` :skull: ,
- our rollup build tries to parse the binary code from `fsevent.node`,
- it fails and crashes.
This is why this PR excludes `fsevents` from the bundle.
We could exclude nunjucks or chokidar but I went for the safest solution because I don't know much about nunjucks or chokidar (although chokidar is meant to …
=> fix(rollup): prevent build failure on MacOS

docs/setup-systems.md
Fixes #788
- Updates setup instructions now that `clever-tools` is part of the stable branch (`24.11` release).
=> docs(setup-systems): add nix stable channel

src/commands/addon.js, src/commands/console.js, src/commands/curl.js, src/models/configuration.js, src/models/send-to-api.js
As discussed previously, this PR defines a `const` with URLs we need in multiple parts of the CLI to define them once, use them when needed and make update easier.
=> refactor: reorganize config variables and declare new ones for common URLs

README.md, bin/clever.js, docs/README.md, docs/addons-backups.md, docs/applications-config.md, docs/kv.md, package-lock.json, package.json, src/commands/addon.js, src/commands/kv.js, src/experimental-features.js, src/models/configuration.js, src/models/ids-resolver.js
⚠️ This is an experimental project to show how easy it is to include native MateriaKV DB support to an application through the Redis API compatiblity layer ⚠️ 
Documentation is available [here](https://github.com/CleverCloud/clever-tools/blob/davlgd-embedded-kv-client/docs/kv.md).
=> Clever native KV support

bin/clever.js, src/commands/profile.js
This PR allow an user to open his user profile in the console with the command `clever profile open`. I also make texts the same for such commands.
=> feat(profile): open in the Console

templates/dockerhub/Dockerfile, templates/dockerhub/README.md
This is the work of @chmuche
https://github.com/CleverCloud/clever-tools-dockerhub/pull/6
but applied on the docker template
* build test image `docker build -t cc:test templates/dockerhub/test`
* start container `docker run --rm -it --entrypoint sh cc:test`
* use `curl` should work: `curl http://example.com`
* use `jq` should work: `echo '{"hello":"jq"}' | jq`
=> feat(docker): add curl and jq binaries

docs/setup-systems.md
Fixes #869
- Removes `Chocolatey` from Windows setup options
The [`chocolatey` package](https://community.chocolatey.org/packages/clever-tools) is outdated (`0.10.1` from 2018). 
We need to discuss if we want to maintain it there but in the meantime it would be better to simply remove this option from the setup docs.
=> docs(setup-systems): remove `Chocolatey` from Windows setup options

src/commands/link.js
Try to link an app with and app ID and an empty or (in)valid org. The user is warned the org is ignored as before, but it works even if the org doesn't exist. 
fixes #889
=> fix: ignore org ID when using an app_id

src/experimental-features.js
This PR updates doc link for NG in experimental features instructions
=> chore: update Network Groups doc link in experimental features instructions

src/commands/tokens.js
This PR uses the latest update from the auth-backend: the `state` property for each token. Once an API token is expired, the associated OAuth tokens are revoked but the API token is still stored in the store so we can list it with a `EXPIRED` state.
This PR adds a `state` column in the `human` format of `clever tokens`.
FYI, the `json` format already displays the `state`.
Before:
```
┌─────────┬──────────────────────────────────────────────────┬────────┬─────────────────────┬────────────────────┬────────────────────┐
│ (index) │                   API token ID                   │  Name  │ Creation IP address │      Creation      │     Expiration     │
├─────────┼──────────────────────────────────────────────────┼────────┼─────────────────────┼────────────────────┼────────────────────┤
│ …
```
=> feat(tokens): add "state" in tokens list

bin/clever.js, src/commands/console.js, src/commands/emails.js, src/commands/open.js, src/commands/profile.js, src/models/utils.js, src/parsers.js
This PR adds an `emails` commands to add, remove(-all) secondary emails to a user account, set the primary email, list emails, and open the emails management page in the Console. 
I've added an email parser to validate emails. It uses a simple regex to avoid corner cases. There is another proposition in comment, chose the one you prefer. 
This PR includes a new utils to open a browser page.
=> feat: add emails command

bin/clever.js, src/commands/ssh-keys.js
This PR adds a `ssh-keys` command, to add, remove(-all), list SSH keys from a user account and to open the SSH Keys panel from the Console. 
If no SSH keys are found, instructions to create one are printed.
=> feat: add ssh-keys command

bin/clever.js
As we removed the `list` command, we should add `format` as private option to `emails` and `ssh-keys` to be able to `clever emails -F json` or `clever ssh-keys --format json`
=> Add JSON format to emails/ssh-keys list command

src/models/log-v4.js
This PR fix the issue with colored lines in logs, adding the ANSI escape sequence to reset text formatting and not printing empty lines with only this sequence.
=> fix: logs with color

src/commands/create.js, src/commands/deploy.js
As we use `Application ID` in create/deploy, we should also use `Organisation ID` and not `Org ID`
=> chore: Org ID to Organisation ID

package.json
Currently, if a user want to use from `npm exec` or `npx`, he should:
```
npm exec --package clever-tools@version clever version
```
or 
```
npx --package clever-tools@version -c 'clever version'
npx --package clever-tools@version -- clever version
```
This PR introduces `clever-tools` as binary for Clever Tools. As package name corresponds to an available binary, users will be able to launch it with:
```
npx clever-tools@version version
```
From `npm help exec` :
> If no --package options are provided, then npm will attempt to determine the executable name from the package specifier provided as the first positional argument according to the following heuristic:
> 
> - If the package has a single entry in its bin field in package.json, or if all entries are aliases of the same command, …
=> feat: add 'clever-tools' as binary

bin/clever.js
This PR remove duplicate `--format` option for operators `version check command`. 
For example: 
```
clever otoroshi version check --help
Usage: check  ADDON-ID
Check Otoroshi deployed version
Arguments:
ADDON-ID                  Add-on ID (or name, if unambiguous)
Options:
[--help, -?]              Display help about this program (default: false)
[--version, -V]           Display the version of this program (default: false)
[--color]                 Choose whether to print colors or not. You can also use --no-color (default: true)
[--update-notifier]       Choose whether to use update notifier or not. You can also use --no-update-notifier (default: true)
[--verbose, -v]           Verbose output (default: false)
[--format, -F] FORMAT     Output format (human, json) (default: human) …
```
=> fix: remove duplicate --format option for operators version check

src/commands/service.js, src/logger.js, src/models/addon.js
Currently, `clever service` responds with linked apps but all add-ons (linked or not) by default. It should be linked apps and linked add-ons, except if `--show-all` is `true`.
This PR:
- returns only linked add-ons, except if `--show-all` is `true` (currently it's only if it's `null`)
- adds `isLinked: true` property to linked add-ons (to print the `*` in the human format list)
To reproduce, use `clever service --app app_id` with/without `--show-all` option
The modified function is only used by this `clever service` feature, so there won't be any other changes linked to this.
I've also added a clearer `human` message if nothing is found (which will now be the common case) with a `Logger.printInfo()` we could use in other commands later. 
Fixes #934
=> fix(service): only print linked add-ons if --show-all is not true

.github/workflows/build.yml, .github/workflows/preview-publish.yml, .github/workflows/release.yml, rollup.config.js, scripts/bundle-cjs.js, scripts/lib/bundle-cjs.js, scripts/preview.js, scripts/publish-winget.js
CI fixes
- add isPreview parameter to build workflow so we only get `preview-` in preview builds
- add AUR to known hosts in release workflow so we can publish to AUR
- use `CI_TOKEN` instead of `GITHUB_TOKEN` for Winget publication
=> Fix CI build

scripts/templates/aur/.SRCINFO
- Add missing AUR package template with metadata and source configuration 
- Include .SRCINFO template for Arch User Repository packaging 
- Add placeholder variables for package metadata, version, and source URL
- Added `scripts/templates/aur/.SRCINFO` template file 
- Template includes proper AUR package metadata structure 
- Enables automated AUR package generation in CI pipeline
- Fixes missing AUR packaging template in CI process 
- Improves distribution support for Arch Linux users
=> fix(ci): add missing AUR package template with metadata

src/models/log-v4.js
Sometimes, it takes longer to get logs at 1st deployment and it leads to an error. 
After some tests, I found a way to prevent this: 
- Define `initRetryTimeout` to increase wait between retries
- Increase try count
=> fix(logs): increase retryConfiguration

bin/clever.js
Closes https://github.com/CleverCloud/clever-tools/issues/949
Mostly based on #950, thank you @sehnryr :+1: :muscle: 
- Show help automatically when no callback is set for a command
- Replace custom console.info with standard help message display in database commands
This refactoring standardizes help message handling across the CLI and provides more consistent user guidance.
@sehnryr Here's what I changed:
- rebase on latest master (the big summer changes introduced prettier so there were merge conflicts :p)
- rename commits to refactor as for users it's not a fix
- I reworked some JS here and there
- I updated the description of the `clever database` command since it does not list
=> refactor: improve help message behavior for root commands without implementation
